# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Danny White
description: >- # this means to ignore newlines until "baseurl:"
  Danny White is a digital designer working in climate mobilisation and
  sustainability.
url: "https://dannywhite.site" # the base hostname & protocol for your site, e.g. http://example.com
author: Danny White

# Build settings
markdown: kramdown

# Stop Apple's emoji preference
kramdown:
  footnote_backlink: "&#8617;&#65038;"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  posts:
    output: true
    permalink: /notes/:year/:title
  projects:
    output: true
    permalink: /projects/:title
    order:
      - time-is-running-out.md
      - environmental-resources-center.md
      - native-checkout.md
      - loupe.md
      - kickstarter-sketch-plugin.md
      - origami.md
      - contextkit
      - branded-interactions.md
  books:
    output: false

# Exclude directories and/or files from the conversion
exclude:
  - Gemfile
  - Gemfile.lock

# Handling drafts
show_drafts: false
