title: Danny White
description:
  Danny White is a digital product designer working on climate mobilisation and
  sustainability.
url: "https://dannywhite.org" # the base hostname & protocol for your site, e.g. http://example.com
author: Danny White

# Build settings
sass:
  style: compressed
compress_html:
  comments: ["<!-- ", " -->"]
  blanklines: true

kramdown:
  # Stop Apple's emoji preference
  footnote_backlink: "&#8617;&#65038;"
  # auto_ids: false: would prevent automatic ids for h2, h3, etc
  auto_ids: true

plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  cheatsheets:
    output: true
    permalink: /cheatsheets/:title
  posts:
    output: true
    permalink: /notes/:year/:title
  work:
    # output: true
    output: false
    permalink: /work/:title
    order:
      - time-is-running-out.md
      - environmental-resources-center.md
      - native-checkout.md
      - loupe-2018.md
      - kickstarter-sketch-plugin.md
      - origami-studio.md
      - contextkit.md
      - branded-interactions.md
      - syd.md
      - mumford.md

# Set some defaults to save repetition
defaults:
  - scope:
      path: ""
      type: "cheatsheets"
    values:
      layout: "cheatsheet"
      type: "article"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      type: "article"
  - scope:
      path: ""
      type: "work"
    values:
      layout: "work"
      type: "article"
      twitter_card_type: "summary_large_image"

# Exclude directories and/or files from the conversion
exclude:
  - Gemfile
  - Gemfile.lock

# Filtering content
show_drafts: false
# future: false
